// Use REST Client extension
// this is a variable
@baseURL = http://localhost:3000

### AppControllerGetHome
# @name AppControllerGetHome
GET {{baseURL}}/home

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseURL}}/home/hello

### ManualConceptsControllerGetManualConceptsMessage
# @name ManualConceptsController
GET {{baseURL}}/manual-concepts

### AutomaticConceptsControllerGetAutomaticConceptsMessage
# @name AutomaticConceptsController
GET {{baseURL}}/automatic-concepts